export const europe_data = [
    ["Country"],
    ["Iceland"],
    ["United Kingdom"],
    ["Ireland"],
    ["Norway"],
    ["Sweden"],
    ["Finland"],
    ["Russia"],
    ["Estonia"],
    ["Latvia"],
    ["Lithuania"],
    ["Belarus"],
    ["Poland"],
    ["Denmark"],
    ["Germany"],
    ["Belgium"],
    ["Netherlands"],
    ["Luxembourg"],
    ["France"],
    ["Spain"],
    ["Portugal"],
    ["Switzerland"],
    ["Italy"],
    ["Malta"],
    ["Slovenia"],
    ["Austria"],
    ["Czech Republic"],
    ["Slovakia"],
    ["Hungary"],
    ["Ukraine"],
    ["Moldova"],
    ["Romania"],
    ["Bulgaria"],
    ["Greece"],
    ["Macedonia"],
    ["Albania"],
    ["Montenegro"],
    ["Serbia"],
    ["Kosovo"],
    ["Croatia"],
    ["Bosnia and Herzegovina"]
];
  
export const europe_options = {
    region: "150",
    backgroundColor: "#81d4fa",
    datalessRegionColor: "grey",
    defaultColor: "#7eca7e",
  };
  
export const micro_europe_data = [
    ["Country"],
    ["Monaco"],
    ["Andorra"],
    ["Liechtenstein"],
    ["San Marino"],
    ['Holy See'],
    ["Malta"],
  ];

export const micro_europe_options = {
    region: "150",
    backgroundColor: "transparent",
    datalessRegionColor: "transpartent",
    defaultColor: "#7eca7e",
  };
