[
{"country" : "Albania", "dish" : "Tavë kosi"},
{"country" : "Andorra", "dish" : "Escudella"},
{"country" : "Austria", "dish" : "Wiener schnitzel, Tafelspitz"},
{"country" : "Belarus", "dish" : "Draniki"},
{"country" : "Belgium", "dish" : "Moules-frites  "},
{"country" : "Bolivia", "dish" : "Salteñas  "},
{"country" : "Bosnia and Herzegovina", "dish" : "Bosnian pot  "},
{"country" : "Bulgaria", "dish" : "Banitsa, Bob chorba"},
{"country" : "Croatia", "dish" : "Istrian stew"},
{"country" : "Cyprus", "dish" : "Fasolada"},
{"country" : "Czech Republic", "dish" : "roast pork with dumplings and sauerkraut"},
{"country" : "Denmark", "dish" : "fried pork and potato-based dish"},
{"country" : "Estonia", "dish" : "verivorst"},
{"country" : "Finland", "dish" : "Karjalanpaisti,  Mämmi, Sautéed reindeer"},
{"country" : "France", "dish" : "Crêpe, Pot-au-feu,  Macaron, Bisque"},
{"country" : "Georgia", "dish" : "Khachapuri, khinkali"},
{"country" : "Germany", "dish" : "Currywurst, Sauerbraten,   Bratwurst "},
{"country" : "Greece", "dish" : "Fasolada,  Moussaka,   Souvlaki "},
{"country" : "Holy See", "dish" : "Fettuccine Alla Papalina"},
{"country" : "Hungary", "dish" : "Gulyás,  "},
{"country" : "Iceland", "dish" : "Hákarl, Þorramatur"},
{"country" : "Ireland", "dish" : "Colcannon,  Irish stew "},
{"country" : "Italy", "dish" : "Ragu alla Bolognese"},
{"country" : "Kosovo", "dish" : "Flia"},
{"country" : "Latvia", "dish" : "Latke"},
{"country" : "Liechtenstein", "dish" : "Käsknöpfle"},
{"country" : "Lithuania", "dish" : "Cepelinai"},
{"country" : "Luxembourg", "dish" : "Judd mat Gaardebounen,   Bouneschlupp"},
{"country" : "Macedonia", "dish" : "Tavče Gravče"},
{"country" : "Malta", "dish" : "Pastizzi, Rabbit Stew (Fenkata)"},
{"country" : "Monaco", "dish" : "Barbagiuan  "},
{"country" : "Montenegro", "dish" : "Kačamak, Raštan  "},
{"country" : "Moldova", "dish" : "Mămăligă, Sarmale, Mici"},
{"country" : "Netherlands", "dish" : "Stamppot, hutspot"},
{"country" : "Norway", "dish" : "Fårikål"},
{"country" : "Poland", "dish" : "Bigos, Pierogi,  Kotlet schabowy,   Żurek"},
{"country" : "Portugal", "dish" : "Bacalhau"},
{"country" : "Romania ", "dish" : "Mămăligă, Sarmale, Mici  "},
{"country" : "Russia", "dish" : "Pelmeni, Shchi, Kasha,  Pirogi, Pirozhki "},
{"country" : "San Marino", "dish" : "Torta Tre Monti"},
{"country" : "Serbia", "dish" : "Ćevapčići, Pljeskavica, Ražnjići, Proja, Kajmak "},
{"country" : "Slovakia", "dish" : "Bryndzové halušky  "},
{"country" : "Slovenia", "dish" : "Ajdovi žganci, Belokranjska povitica, Obara"},
{"country" : "Spain", "dish" : "Tortilla española   "},
{"country" : "Sweden", "dish" : "Köttbullar,   Kräftskiva,  Surströmming,  Ostkaka  "},
{"country" : "Switzerland", "dish" : "Cervelat,  Fondue, Rösti"},
{"country" : "Turkey", "dish" : "Döner kebab,   Kuru fasulye with pilav "},
{"country" : "Ukraine", "dish" : "Borscht,   Varenyky   "},
{"country" : "United Kingdom", "dish" : "Fish and chips, Haggis, Ulster Fry, Cawl  "},
]