use europe 
db.dropDatabase();

// name, flag, capital city, pop, animal, dish, greeting
db.countries.insertMany([
{"country" : "Albania", "dish" : "Tavë kosi", "greeting" : 'Tungjatjeta'},
{"country" : "Andorra", "dish" : "Escudella", "greeting" : 'hola'},
{"country" : "Austria", "dish" : "Wiener schnitzel, Tafelspitz", "greeting" : 'Hallo'},
{"country" : "Belarus", "dish" : "Draniki", "greeting": 'dobry dzień'},
{"country" : "Belgium", "dish" : "Moules-frites", "greeting": 'Hallo'},
{"country" : "Bosnia and Herzegovina", "dish" : "Bosnian pot", "greeting": 'Zdravo'},
{"country" : "Bulgaria", "dish" : "Banitsa, Bob chorba", "greeting": 'Zdravei'},
{"country" : "Croatia", "dish" : "Istrian stew"},
{"country" : "Cyprus", "dish" : "Fasolada", "greeting": ["Yiasoo", "Merhaba"]},
{"country" : "Czech Republic", "dish" : "Roast pork with dumplings and sauerkraut", "greeting": "Ahoj"},
{"country" : "Denmark", "dish" : "Fried pork and potato-based dish", "greeting": "Hej"},
{"country" : "Estonia", "dish" : "Verivorst", "greeting": "Tere"},
{"country" : "Finland", "dish" : "Karjalanpaisti, Mämmi, Sautéed reindeer", "greeting": "Moi"},
{"country" : "France", "dish" : "Crêpe, Pot-au-feu,  Macaron, Bisque", "greeting": "Bonjour"},
{"country" : "Georgia", "dish" : "Khachapuri, khinkali", "greeting" : "Gamarjoba"},
{"country" : "Germany", "dish" : "Currywurst, Sauerbraten, Bratwurst", "greeting": "Hallo"},
{"country" : "Greece", "dish" : "Fasolada,  Moussaka, Souvlaki", "greeting" : "Geia Sas"},
{"country" : "Holy See (Vatican City)", "dish" : "Fettuccine Alla Papalina", "greeting" : "Salve"},
{"country" : "Hungary", "dish" : "Gulyás", "greeting" : "Szia"},
{"country" : "Iceland", "dish" : "Hákarl, Þorramatur" , "greeting" : "Hallo"},
{"country" : "Ireland", "dish" : "Colcannon, Irish stew" , "greeting" : "Hi"},
{"country" : "Italy", "dish" : "Ragu alla Bolognese", "greeting" : "Ciao"},
{"country" : "Kosovo", "dish" : "Flia", "greeting" : "Agim"},
{"country" : "Latvia", "dish" : "Latke", "greeting" : "Sveiki"},
{"country" : "Liechtenstein", "dish" : "Käsknöpfle", "greeting" : "Grüss Gott"},
{"country" : "Lithuania", "dish" : "Cepelinai", "greeting" : "Labas"},
{"country" : "Luxembourg", "dish" : "Judd mat Gaardebounen, Bouneschlupp", "greeting" : "Moien"},
{"country" : "North Macedonia", "dish" : "Tavče Gravče"},
{"country" : "Malta", "dish" : "Pastizzi, Rabbit Stew (Fenkata)"},
{"country" : "Monaco", "dish" : "Barbagiuan" , "greeting" : "Bonjour"},
{"country" : "Montenegro", "dish" : "Kačamak, Raštan", "greeting" : "Zdravo"},
{"country" : "Moldova", "dish" : "Mămăligă, Sarmale, Mici", "greeting" : "Noroc"},
{"country" : "Netherlands", "dish" : "Stamppot, Hutspot", "greeting" : "Hallo"},
{"country" : "Norway", "dish" : "Fårikål", "greeting" : "Hei"},
{"country" : "Poland", "dish" : "Bigos, Pierogi, Kotlet schabowy, Żurek", "greeting" : "Witaj"},
{"country" : "Portugal", "dish" : "Bacalhau" , "greeting" : "Ola"},
{"country" : "Romania ", "dish" : "Mămăligă, Sarmale, Mici", "greeting" : "Buna ziua"},
{"country" : "Russia", "dish" : "Pelmeni, Shchi, Kasha, Pirogi, Pirozhki", "greeting" : "Privet"},
{"country" : "San Marino", "dish" : "Torta Tre Monti", "greeting" : "Ciao"},
{"country" : "Serbia", "dish" : "Ćevapčići, Pljeskavica, Ražnjići, Proja, Kajmak", "greeting" : "Zdravo"},
{"country" : "Slovakia", "dish" : "Bryndzové halušky", "greeting" : "Ahoj"},
{"country" : "Slovenia", "dish" : "Ajdovi žganci, Belokranjska povitica, Obara"}, "greeting" : "Zivjo",
{"country" : "Spain", "dish" : "Tortilla española", "greeting" : "Hola"},
{"country" : "Sweden", "dish" : "Köttbullar, Kräftskiva, Surströmming, Ostkaka", "greeting" : "Halla"},
{"country" : "Switzerland", "dish" : "Cervelat,  Fondue, Rösti", 'greeting': 'Ciao'},
{"country" : "Turkey", "dish" : "Döner kebab, Kuru fasulye with pilav", "greeting" : "Merhaba"},
{"country" : "Ukraine", "dish" : "Borscht, Varenyky", "greeting" : "Vitayu"},
{"country" : "United Kingdom", "dish" : "Fish and chips, Haggis, Ulster Fry, Cawl", "greeting" : "Hello"},
])